# Generated by Django 5.0.4 on 2024-05-21 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TenSP", models.CharField(max_length=100)),
                ("DonGia", models.DecimalField(decimal_places=2, max_digits=10)),
                ("HinhAnh", models.ImageField(blank=True, null=True, upload_to="")),
                ("MoTa", models.CharField(max_length=500)),
                (
                    "ML_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.loai"
                    ),
                ),
            ],
        ),
    ]
